sudo: required

services:
  - docker

before_install:
  - docker build -t workflows-engine-tester .

script:
  - docker run -i -t --rm workflows-engine-tester
  - docker build -t workflows-engine-docs -f ./docs/Dockerfile . # Build runs doctest
